cmdtbl:
    db "help",0
    dd cmd_help
    db "clear",0
    dd cmd_cls
    db "cls",0
    dd cmd_cls
    db "ver",0
    dd cmd_ver
    db "uname",0
    dd cmd_uname
    db "hostname",0
    dd cmd_host
    db "whoami",0
    dd cmd_who
    db "id",0
    dd cmd_id
    db "date",0
    dd cmd_date
    db "uptime",0
    dd cmd_uptime
    db "echo",0
    dd cmd_echo
    db "mem",0
    dd cmd_mem
    db "free",0
    dd cmd_mem
    db "lscpu",0
    dd cmd_lscpu
    db "lspci",0
    dd cmd_lspci
    db "lsusb",0
    dd cmd_lsusb
    db "lsblk",0
    dd cmd_lsblk
    db "dmesg",0
    dd cmd_dmesg
    db "env",0
    dd cmd_env
    db "set",0
    dd cmd_env
    db "color",0
    dd cmd_color
    db "calc",0
    dd cmd_calc
    db "hex",0
    dd cmd_hex
    db "dec",0
    dd cmd_dec
    db "factor",0
    dd cmd_factor
    db "seq",0
    dd cmd_seq
    db "rev",0
    dd cmd_rev
    db "yes",0
    dd cmd_yes
    db "true",0
    dd cmd_true
    db "false",0
    dd cmd_false
    db "sleep",0
    dd cmd_sleep
    db "ps",0
    dd cmd_ps
    db "top",0
    dd cmd_top
    db "kill",0
    dd cmd_kill
    db "ls",0
    dd cmd_ls
    db "dir",0
    dd cmd_ls
    db "cd",0
    dd cmd_cd
    db "pwd",0
    dd cmd_pwd
    db "cat",0
    dd cmd_cat
    db "head",0
    dd cmd_head
    db "tail",0
    dd cmd_tail
    db "wc",0
    dd cmd_wc
    db "grep",0
    dd cmd_grep
    db "sort",0
    dd cmd_sort
    db "uniq",0
    dd cmd_uniq
    db "tac",0
    dd cmd_tac
    db "nl",0
    dd cmd_nl
    db "find",0
    dd cmd_find
    db "tree",0
    dd cmd_tree
    db "stat",0
    dd cmd_stat
    db "touch",0
    dd cmd_touch
    db "mkdir",0
    dd cmd_mkdir
    db "rm",0
    dd cmd_rm
    db "cp",0
    dd cmd_cp
    db "mv",0
    dd cmd_mv
    db "df",0
    dd cmd_df
    db "du",0
    dd cmd_du
    db "chmod",0
    dd cmd_chmod
    db "ln",0
    dd cmd_ln
    db "hexdump",0
    dd cmd_hexdump
    db "od",0
    dd cmd_hexdump
    db "strings",0
    dd cmd_strings
    db "cmp",0
    dd cmd_cmp
    db "basename",0
    dd cmd_base
    db "dirname",0
    dd cmd_dirn
    db "ifconfig",0
    dd cmd_ifc
    db "ip",0
    dd cmd_ifc
    db "ping",0
    dd cmd_ping
    db "netstat",0
    dd cmd_netstat
    db "ss",0
    dd cmd_netstat
    db "arp",0
    dd cmd_arp
    db "route",0
    dd cmd_route
    db "nslookup",0
    dd cmd_ns
    db "dig",0
    dd cmd_ns
    db "host",0
    dd cmd_ns
    db "wget",0
    dd cmd_wget
    db "curl",0
    dd cmd_curl
    db "traceroute",0
    dd cmd_tracert
    db "ssh",0
    dd cmd_ssh
    db "scp",0
    dd cmd_scp
    db "tar",0
    dd cmd_tar
    db "gzip",0
    dd cmd_gzip
    db "gunzip",0
    dd cmd_gzip
    db "zip",0
    dd cmd_zip
    db "unzip",0
    dd cmd_zip
    db "systemctl",0
    dd cmd_svc
    db "journalctl",0
    dd cmd_jctl
    db "service",0
    dd cmd_svc
    db "mount",0
    dd cmd_mount
    db "umount",0
    dd cmd_umount
    db "fdisk",0
    dd cmd_fdisk
    db "blkid",0
    dd cmd_blkid
    db "passwd",0
    dd cmd_pass
    db "useradd",0
    dd cmd_uadd
    db "userdel",0
    dd cmd_udel
    db "su",0
    dd cmd_su
    db "sudo",0
    dd cmd_sudo
    db "groupadd",0
    dd cmd_gadd
    db "reboot",0
    dd cmd_reboot
    db "halt",0
    dd cmd_halt
    db "shutdown",0
    dd cmd_halt
    db "history",0
    dd cmd_hist
    db "alias",0
    dd cmd_alias
    db "export",0
    dd cmd_export
    db "read",0
    dd cmd_read
    db "test",0
    dd cmd_test
    db "expr",0
    dd cmd_expr
    db "printf",0
    dd cmd_printf
    db "which",0
    dd cmd_which
    db "type",0
    dd cmd_which
    db "basename",0
    dd cmd_base
    db "cksum",0
    dd cmd_cksum
    db "sum",0
    dd cmd_cksum
    db "md5sum",0
    dd cmd_md5
    db "tee",0
    dd cmd_tee
    db "xargs",0
    dd cmd_xargs
    db "tr",0
    dd cmd_tr
    db "cut",0
    dd cmd_cut
    db "paste",0
    dd cmd_paste
    db "fold",0
    dd cmd_fold
    db "expand",0
    dd cmd_expand
    db "comm",0
    dd cmd_comm
    db "diff",0
    dd cmd_diff
    db "cowsay",0
    dd cmd_cow
    db "matrix",0
    dd cmd_matrix
    db "neofetch",0
    dd cmd_neo
    db "banner",0
    dd cmd_banner
    db "fortune",0
    dd cmd_fort
    db "sl",0
    dd cmd_sl
    db "cmatrix",0
    dd cmd_matrix
    db "figlet",0
    dd cmd_fig
    db "gui",0
    dd cmd_gui
    db "about",0
    dd cmd_about
    db "gcc",0
    dd cmd_gcc
    db "make",0
    dd cmd_make
    db "python",0
    dd cmd_python
    db "node",0
    dd cmd_node
    db "git",0
    dd cmd_git
    db "java",0
    dd cmd_java
    db "dotnet",0
    dd cmd_dotnet
    db "nmap",0
    dd cmd_nmap
    db "tcpdump",0
    dd cmd_tcpdump
    db "iptables",0
    dd cmd_iptables
    db "apt",0
    dd cmd_apt
    db "yum",0
    dd cmd_yum
    db "dnf",0
    dd cmd_yum
    db "pacman",0
    dd cmd_pac
    db "snap",0
    dd cmd_snap
    db "pip",0
    dd cmd_pip
    db "npm",0
    dd cmd_npm
    db "chown",0
    dd cmd_chown
    db "nohup",0
    dd cmd_nohup
    db "timeout",0
    dd cmd_timeout
    db "nice",0
    dd cmd_nice
    db "renice",0
    dd cmd_nice
    db "jobs",0
    dd cmd_jobs
    db "bg",0
    dd cmd_bg
    db "fg",0
    dd cmd_fg
    db "alias",0
    dd cmd_alias
    db "unalias",0
    dd cmd_alias
    db "source",0
    dd cmd_source
    db ".",0
    dd cmd_source
    db "sh",0
    dd cmd_sh
    db "bash",0
    dd cmd_sh
    db "exit",0
    dd cmd_exit
    db "quit",0
    dd cmd_exit
    db "logout",0
    dd cmd_exit
    db "man",0
    dd cmd_man
    db "info",0
    dd cmd_man
    db "apropos",0
    dd cmd_man
    db "tldr",0
    dd cmd_man
    db 0
